DROP FUNCTION IF EXISTS getFriendlyName
;
CREATE FUNCTION getFriendlyName(pv_centre_id VARCHAR(30)) RETURNS varchar(100) CHARSET utf8
BEGIN
      DECLARE friendly_name VARCHAR(100);
  DECLARE centre_name VARCHAR(100);
  
  SELECT 
    CENTRENAME, 
    (SELECT ca.ATTRIBUTEVALUE FROM centreattribute ca WHERE ca.ID = c.ID and ca.ATTRIBUTENAME = 'FRIENDLYNAME' ) AS ATTRIBUTEVALUE
  INTO
    centre_name,
    friendly_name
  FROM
    centre c
  WHERE 
    c.ID = pv_centre_id;
  
      RETURN IFNULL(friendly_name, centre_name);
END
;


DROP FUNCTION IF EXISTS getAgeAtMainDate
;
CREATE FUNCTION getAgeAtMainDate(mce_id INT unsigned) RETURNS INT
BEGIN
  DECLARE age INT;
	select 
    floor(datediff(i.INTERVENTION_DATE, p.BIRTH_DATE) / 365.25) as age
    from mce m, patient p, intervention i where m.PID = p.PID and mce_id = m.MCEID and i.MCEID = mce_id into age;  
  RETURN (age);
END
;


DROP FUNCTION IF EXISTS getMainDate
;
CREATE FUNCTION getMainDate (pn_mceid INT UNSIGNED) RETURNS DATE
BEGIN
	DECLARE ld_main_date DATE; 
  
  SELECT intervention.INTERVENTION_DATE INTO ld_main_date FROM intervention WHERE MCEID = pn_mceid;
     
	RETURN ld_main_date;
END
;

DROP FUNCTION IF EXISTS getListText
;
CREATE FUNCTION getListText(var_name VARCHAR(100), item_no TINYINT) RETURNS varchar(100) CHARSET utf8
BEGIN
  DECLARE text_key VARCHAR(150);
  DECLARE ret_val VARCHAR(100);
  SET text_key = CONCAT(var_name, '_L');
  select t.text from listboxtextrow lt, text t where t.ID = lt.TEXTID AND lt.TEXTVALUE = CONCAT('', item_no) AND lt.ID = text_key and t.LANGUAGEID = 'no' INTO ret_val;
  RETURN (ret_val);
END
;


DROP FUNCTION IF EXISTS getCheckText
;
CREATE FUNCTION getCheckText(value TINYINT) RETURNS varchar(5) CHARSET utf8
BEGIN
  DECLARE ret_val VARCHAR(5);
  IF value = 1 THEN
    SET ret_val = 'Ja';
  ELSE
    SET ret_val = 'Nei';
  END IF;
  RETURN (ret_val);
END
;


DROP FUNCTION IF EXISTS getStatusText
;
CREATE FUNCTION getStatusText(value TINYINT) RETURNS varchar(15) CHARSET utf8
BEGIN
  DECLARE ret_val VARCHAR(15);
  IF value = 1 THEN
    SET ret_val = 'Ferdigstilt';
  ELSEIF value = -1 THEN
    SET ret_val = 'Opprettet';
  ELSEIF value = 0 THEN
    SET ret_val = 'Kladd';
  ELSEIF value = 10 THEN
    SET ret_val = 'Kansellert';
  ELSE
    SET ret_val = 'Ukjent';
  END IF;
  RETURN (ret_val);
END
;



    
drop view if exists SkjemaOversikt;
create view SkjemaOversikt AS
select 
  'Pasient' AS SkjemaNavn,
  skjema.STATUS AS SkjemaStatus,
  m.MCEID AS ForlopsID, 
  skjema.CREATEDBY AS OpprettetAv,
  skjema.TSCREATED AS OpprettetDato,
  skjema.UPDATEDBY AS SistLagretAv,
  skjema.TSUPDATED AS SistLagretDato,
  getMainDate(m.MCEID) AS HovedDato,
  getFriendlyName(c.ID) AS SykehusNavn,
  c.ID AS AvdRESH,
  1 as SkjemaRekkeflg
from
  patient skjema,
  mce m,
  registration r,  
  centre c
WHERE skjema.PID = m.PID and r.MCEID = m.MCEID and skjema.CENTREID = c.ID  
UNION
select 
  'Preintervensjon' AS Skjemanavn,
  skjema.STATUS AS SkjemaStatus,
  skjema.MCEID AS ForlopsID, 
  skjema.CREATEDBY AS OpprettetAv,
  skjema.TSCREATED AS OpprettetDato,
  skjema.UPDATEDBY AS SistLagretAv,
  skjema.TSUPDATED AS SistLagretDato,
  getMainDate(skjema.MCEID) AS HovedDato,
  getFriendlyName(c.ID) AS Sykehusnavn,
  c.ID AS AvdRESH, 
  3 as SkjemaRekkeflg
from
  preintervention skjema,
  centre c
WHERE skjema.CENTREID = c.ID  
UNION
select 
  'Intervensjon' AS Skjemanavn,
  skjema.STATUS AS SkjemaStatus,
  skjema.MCEID AS ForlopsID, 
  skjema.CREATEDBY AS OpprettetAv,
  skjema.TSCREATED AS OpprettetDato,
  skjema.UPDATEDBY AS SistLagretAv,
  skjema.TSUPDATED AS SistLagretDato,
  getMainDate(skjema.MCEID) AS HovedDato,
  getFriendlyName(c.ID) AS Sykehusnavn,
  c.ID AS AvdRESH,
  5 as SkjemaRekkeflg
from
  intervention skjema,
  centre c
WHERE skjema.CENTREID = c.ID
UNION
select 
  'Kontroll 6 mnd' AS Skjemanavn,
  skjema.STATUS AS SkjemaStatus,
  skjema.MCEID AS ForlopsID, 
  skjema.CREATEDBY AS OpprettetAv,
  skjema.TSCREATED AS OpprettetDato,
  skjema.UPDATEDBY AS SistLagretAv,
  skjema.TSUPDATED AS SistLagretDato,
  getMainDate(skjema.MCEID) AS HovedDato,
  getFriendlyName(c.ID) AS Sykehusnavn,
  c.ID AS AvdRESH,
  9 as SkjemaRekkeflg
from
  control skjema,
  centre c
WHERE skjema.CENTREID = c.ID and skjema.STATUS > -2;



drop view if exists ForlopsOversikt;
create view ForlopsOversikt AS  
  
  select    
    reg.CENTREID AS AvdRESH,
    getFriendlyName(reg.CENTREID) AS SykehusNavn,  
    p.PID AS PasientID, 
--     p.ZIPCODE AS PostNr,
    null as PostNr,
    null as PostSted,
    null as Kommune,
--     p.MUNICIPALITY as KommuneNr,
    null as KommuneNr,    
    null as Fylke,    
    null as FylkeNr,   
    p.SSN as KryptertFnr,
    getListText('PATIENT_GENDER', p.GENDER) AS PasientKjonn,    
    p.GENDER AS ErMann,         
    getAgeAtMainDate(m.MCEID) AS PasientAlder,
    null as Norsktalende,
    null as Sivilstatus,
    null as Utdanning,
    null as Avdod,
    null as AvdodDato,
    i.INTERVENTION_DATE AS HovedDato,                                
    m.MCEID AS ForlopsID,
    getListText('INTERVENTION_TYPE_INTERVENTION', i.TYPE_INTERVENTION) AS ForlopsType1,
    i.TYPE_INTERVENTION as ForlopsType1Num,    
    getListText('INTERVENTION_SURGERY_TYPE', i.SURGERY_TYPE) AS ForlopsType2,       
    i.SURGERY_TYPE AS ForlopsType2Num,  
    null as KobletForlopsID,
--     CAST(0 as char) AS ErOppflg,    
--     CAST(
--       (SELECT CASE
--         WHEN i.TYPE_INTERVENTION = 1 THEN 
--           ctrl6.DO_MONTH
--         WHEN i.TYPE_INTERVENTION = 2 THEN       
--           COALESCE(ctrl24.DO_MONTH, ctrl21.DO_MONTH, ctrl18.DO_MONTH, ctrl15.DO_MONTH, ctrl12.DO_MONTH, ctrl9.DO_MONTH, ctrl6.DO_MONTH, ctrl3.DO_MONTH)
--         WHEN i.TYPE_INTERVENTION = 3 THEN  
--           COALESCE(ctrl24.DO_MONTH, ctrl21.DO_MONTH, ctrl18.DO_MONTH, ctrl15.DO_MONTH, ctrl12.DO_MONTH, ctrl9.DO_MONTH, ctrl6.DO_MONTH, ctrl3.DO_MONTH)
--         ELSE 
--           NULL -- no followups
--         END 
--       )  AS SIGNED) AS OppflgSekNr, -- For now. Returns the highest relevant month. 24 or 6.
      6 as OppflgSekNr,
--     CAST(
--       (SELECT CASE
--         WHEN i.TYPE_INTERVENTION = 1 THEN 
--           ifnull(ctrl6.STATUS, -2)
--         WHEN i.TYPE_INTERVENTION = 2 THEN       
--           ifnull(LEAST(ctrl3.STATUS, ctrl6.STATUS, ctrl9.STATUS, ctrl12.STATUS, ctrl15.STATUS, ctrl18.STATUS, ctrl21.STATUS, ctrl24.STATUS), -2)
--         WHEN i.TYPE_INTERVENTION = 3 THEN  
--           ifnull(LEAST(ctrl3.STATUS, ctrl6.STATUS, ctrl9.STATUS, ctrl12.STATUS, ctrl15.STATUS, ctrl18.STATUS, ctrl21.STATUS, ctrl24.STATUS), -2)
--         ELSE 
--           2 -- no followups
--         END 
--       )  AS SIGNED) AS OppflgRegStatus
      ctrl6.STATUS as OppflgRegStatus
 from
    mce m INNER JOIN patient p ON m.PID = p.PID
    INNER JOIN registration reg on m.MCEID = reg.MCEID
    INNER JOIN preintervention pre on m.MCEID = pre.MCEID
    INNER JOIN intervention i on m.MCEID = i.MCEID    
    INNER JOIN user u ON m.CREATEDBY = u.ID
    LEFT OUTER JOIN control ctrl6 on m.MCEID = ctrl6.MCEID AND ctrl6.STATUS > -2
where p.STATUS > 0 AND i.STATUS > 0 AND pre.STATUS > 0;
--     LEFT OUTER JOIN control ctrl3 on m.MCEID = ctrl3.MCEID and ctrl3.DO_MONTH = 3 AND ctrl3.STATUS > -2
--     LEFT OUTER JOIN control ctrl6 on m.MCEID = ctrl6.MCEID and ctrl6.DO_MONTH = 6 AND ctrl6.STATUS > -2
--     LEFT OUTER JOIN control ctrl9 on m.MCEID = ctrl9.MCEID and ctrl9.DO_MONTH = 9 AND ctrl9.STATUS > -2
--     LEFT OUTER JOIN control ctrl12 on m.MCEID = ctrl12.MCEID and ctrl12.DO_MONTH = 12 AND ctrl12.STATUS > -2
--     LEFT OUTER JOIN control ctrl15 on m.MCEID = ctrl15.MCEID and ctrl15.DO_MONTH = 15 AND ctrl15.STATUS > -2
--     LEFT OUTER JOIN control ctrl18 on m.MCEID = ctrl18.MCEID and ctrl18.DO_MONTH = 18 AND ctrl18.STATUS > -2
--     LEFT OUTER JOIN control ctrl21 on m.MCEID = ctrl21.MCEID and ctrl21.DO_MONTH = 21 AND ctrl21.STATUS > -2
--     LEFT OUTER JOIN control ctrl24 on m.MCEID = ctrl24.MCEID and ctrl24.DO_MONTH = 24 AND ctrl24.STATUS > -2; 

    
DROP VIEW IF EXISTS AlleVarNum; 
CREATE VIEW AlleVarNum AS
SELECT
  mce.MCEID as m_mceid, 
  mce.PID as m_pid, 
  registration.CENTREID as r_resh_id, 
  patient.ACCEPTANCE as p_acceptance, 
  patient.GENDER as p_gender,
  patient.EDUCATION as p_education, 
  patient.HIGHT as p_height, 
  patient.WEIGHT as p_weight,
--   patient.ZIPCODE as p_zipcode,
  null as p_zipcode,
--   patient.MUNICIPALITY as p_municipality,
  null as p_municipality,
  patient.AGE_ABSCESS as p_age_abscess, 
  patient.TIME_SPECIALIST as p_time_specialist, 
  patient.FIRST_TIME_SPECIALIST as p_first_time_specialist, 
  patient.ANTIBIOTICS as p_antibiotics, 
  patient.SURGERY as p_surgery, 
--   patient.FAMILY_ILLNES as p_family_illness,
  null as p_family_illness,
--   patient.ACNE as p_acne,
  null as p_acne,
--   patient.ISOTRETINOIN as p_isotretinoin,
  null as p_isotretinoin,
--   patient.SKINDISEASES as p_skindiseases,
  null as p_skindiseases,
--   patient.MENTAL_DISORDERS as p_mental_disorders,
  null as p_mental_disorders,
--   patient.GASTROINTESTINAL_DISEASES as p_gastro_diseases,
  null as p_gastro_diseases,
--   patient.DIABETES as p_diabetes,  
  null as p_diabetes,  
--   patient.BLOOD_TESTS as p_bloodtests,
  null as p_bloodtests,
--   patient.HB as p_hb,
  null as p_hb,
--   patient.WHITE_BLOODCELLS as p_white_bloodcells,
  null as p_white_bloodcells,
--   patient.CRP as p_crp,
  null as p_crp,
--   patient.ASAT as p_asat,
  null as p_asat,
--   patient.ALAT as p_alat,
  null as p_alat,
--   patient.CREATININE as p_creatinine,
  null as p_creatinine,
--   patient.CHOLESTEROL as p_cholesterol,
  null as p_cholesterol,
--   patient.HDL as p_hdl,
  null as p_hdl,
--   patient.TRIGLYCERIDES as p_triglycerides,
  null as p_triglycerides,
--   patient.FASTING_BLOOD_SUGAR as p_blood_sugar,
  null as p_blood_sugar,
--   patient.BLOOD_PRESSURE as p_bloodpressure,
  null as p_bloodpressure,
--   patient.SYSTOLIC as p_systolic,
  null as p_systolic,
--   patient.DIASTOLIC as p_diastolic,  
  null as p_diastolic,  
  patient.STATUS as p_status, 
  preintervention.CENTREID as pre_centreid, 
  preintervention.PREINTERVENTION_DATE as pre_date, 
  preintervention.ABSCESS as pre_abscess, 
  preintervention.ABSCESS_PAIN as pre_abscess_pain, 
  preintervention.VASSCORE as pre_vasscore, 
  preintervention.WORK as pre_work, 
  preintervention.SMOKING as pre_smoking, 
  preintervention.HIGHT AS pre_height, 
  preintervention.WEIGHT as pre_weight, 
--   preintervention.BMI as pre_bmi, 
  null as pre_bmi, 
  preintervention.SORNESS pre_soreness, 
  preintervention.EMBARRESSED as pre_embarressed, 
  preintervention.PREVENT_DAILY_WORK as pre_prevent_daily_work, 
  preintervention.CLOTHING_OPTION as pre_clothing_option, 
  preintervention.SOCIAL_LIFE as pre_social_life, 
  preintervention.ATHLETIC_ACTIVITY as pre_athletic_activity, 
  preintervention.PREVENT_WORK as pre_prevent_work, 
  preintervention.WORK_PROBLEMS as pre_work_problems, 
  preintervention.PARTNER_PROBLEMS as pre_partner_problems, 
  preintervention.SEXUAL_PROBLEMS as pre_sexual_problems, 
  preintervention.PROBLEMS_LAST_WEEK as pre_problems_last_week, 
  preintervention.DLQISUM as pre_dlqisum, 
  preintervention.HURLEY_SCORE as pre_hurley_score, 
  preintervention.RA as pre_ra, 
  preintervention.RAN as pre_ran, 
  preintervention.RAF as pre_raf, 
  preintervention.RALD as pre_rald, 
  preintervention.RAHUR as pre_rahur, 
  preintervention.RG as pre_rg, 
  preintervention.RGN as pre_rgn, 
  preintervention.RGF as pre_rgf, 
  preintervention.RGLD as pre_rgld, 
  preintervention.RGHUR as pre_rghur, 
  preintervention.RGR as pre_rgr, 
  preintervention.RGRN as pre_rgrn, 
  preintervention.RGRF as pre_rgrf, 
  preintervention.RGRLD as pre_rgrld, 
  preintervention.RGRHUR as pre_rgrhur, 
  preintervention.LA as pre_la, 
  preintervention.LAN as pre_lan, 
  preintervention.LAF as pre_laf, 
  preintervention.LALD as pre_lald, 
  preintervention.LAHUR as pre_lahur, 
  preintervention.LG as pre_lg, 
  preintervention.LGN as pre_lgl, 
  preintervention.LGF as pre_lgf, 
  preintervention.LGLD as pre_lgld, 
  preintervention.LGHUR as pre_lghur, 
  preintervention.LGR as pre_lgr, 
  preintervention.LGRN as pre_lgrn, 
  preintervention.LGRF as pre_lgrf, 
  preintervention.LGRLD as pre_lgrld, 
  preintervention.LGRHUR as pre_lgrhur, 
  preintervention.OTHERREGION as pre_otherregion, 
  preintervention.ORN as pre_orn, 
  preintervention.ORF as pre_orf, 
  preintervention.ORLD as pre_orld, 
  preintervention.ORHUR as pre_orhur, 
  preintervention.HSSCORESUM as pre_hsscoresum,
--   preintervention.HISCR_BOILS as pre_hiscr_boils,
  null as pre_hiscr_boils,
--   preintervention.HISCR_INFLAMED as pre_hiscr_inflamed,
  null as pre_hiscr_inflamed,
--   preintervention.HISCR_DRAINING as pre_hiscr_draining,  
  null as pre_hiscr_draining,  
  preintervention.STATUS as pre_status, 
  intervention.CENTREID as i_centreid, 
  intervention.INTERVENTION_DATE as i_date, 
  intervention.TYPE_INTERVENTION as i_type, 
  intervention.SURGERY_TYPE as i_surgery_type, 
  intervention.AKSILLE as i_aksille, 
  intervention.AKSILLE_RIGHT as i_aksille_right, 
  intervention.AKSILLE_LEFT as i_aksille_left, 
  intervention.AKSILLE_UNKNOWN as i_aksille_unknown, 
  intervention.LYSKE as i_lyske, 
  intervention.LYSKE_RIGHT as i_lyske_right, 
  intervention.LYSKE_LEFT as i_lyske_left, 
  intervention.LYSKE_UNKNOWN as i_lyske_unknown, 
  intervention.PUBIS as i_pubis, 
  intervention.PUBIS_RIGHT as i_pubis_left,  
  intervention.PUBIS_LEFT as i_pubis_right, 
  intervention.PUBIS_CENTRAL as i_pubis_central, 
  intervention.PUBIS_UNKNOWN as i_pubis_unknown, 
  intervention.GENITALT as i_genitalt, 
  intervention.GENITALT_RIGHT as i_genitalt_right, 
  intervention.GENITALT_LEFT as i_genitalt_left, 
  intervention.GENITALT_UNKNOWN as i_genitalt_unknown, 
  intervention.PERIALT as i_peritalt, 
  intervention.PERIALT_RIGHT as i_peritalt_right,
  intervention.PERIALT_LEFT as i_peritalt_left, 
  intervention.PERIALT_UNKNOWN as i_peritalt_unknown, 
  intervention.GLUTEALT as i_glutealt, 
  intervention.GLUTEALT_RIGHT as i_glutealt_right,  
  intervention.GLUTEALT_LEFT as i_glutealt_left, 
  intervention.GLUTEALT_CENTRAL as i_glutealt_central, 
  intervention.GLUTEALT_UNKNOWN as i_glutealt_unknown, 
  intervention.MAMMAE as i_mammae, 
  intervention.MAMMAE_RIGHT as i_mammae_right, 
  intervention.MAMMAE_LEFT as i_mammae_left, 
  intervention.MAMMAE_UNKNOWN as i_mammae_unknown, 
  intervention.OTHER_LOCATION as i_other_location, 
  intervention.OTHER_LOCATION_THIGHS as i_other_location_thighs, 
  intervention.OTHER_LOCATION_STOMACH as i_other_location_stomach, 
  intervention.OTHER_LOCATION_BACK as i_other_location_back, 
  intervention.OTHER_LOCATION_NECK as i_other_location_neck, 
  intervention.OTHER_LOCATION_OTHER as i_other_location_other, 
  intervention.OTHER_LOCATION_OTHER_TEXT as i_other_location_other_text, 
  intervention.BIOLOGICAL_TREATMENT as i_biological_treatment, 
  intervention.OTHER_BIOLOGICAL_TREATMENT as i_other_biological_treatment, 
  intervention.SYSTEMIC_ANTIBIOTIC_THERAPY as i_antibiotic_therapy, 
  intervention.RIFAMPICIN_CLINDAMYCIN as i_rifampicin_clindamycin, 
  intervention.TETRACYCLIN_LYMECYCLIN as i_tetracyclin_lymecyclin, 
  intervention.SYSTEMIC_ANTIBIOTIC_THERAPY_OTHER as i_sys_antibiotic_other, 
  intervention.OTHER_SYSTEMIC_ANTIBIOTIC_THERAPY as i_other_sys_antibiotic, 
  intervention.ANTIINFLAMMATORY_TREATMENT as i_antiinflammatory_treatment, 
  intervention.OTHER_ANTIINFLAMMATORY_TREATMENT as i_other_antiinflammatory_treatment, 
  intervention.ANALGESICS as i_analgesics, 
  intervention.OTHER_ANALGESICS as i_other_analgesics, 
  intervention.BASED_MEDICAL_TREATMENT as i_localized_med_treatment , 
  intervention.INTRALESIONAL_CORTICOSTEROID_INJECTION as i_corticosteroid_injection, 
  intervention.ACELACIC_ACID as i_acelacic_acid, 
  intervention.CLINDAMYCIN as i_clindamycin, 
  intervention.RESORCINOL as i_resorcinol, 
  intervention.AMOXICILIN as i_amoxicilin, 
  intervention.MEDICAL_INT_OTHER as i_medical_other, 
  intervention.MEDICAL_INT_OTHER_TEXT as i_medical_other_text, 
  intervention.STATUS as i_status, 
  
--   ctrl3month.CENTREID as c3_centreid, 
--   ctrl3month.DO_MONTH as c3_do_month, 
--   ctrl3month.CONTROL_DATE as c3_date, 
--   ctrl3month.POSSIBLE as c3_possible,
--   ctrl3month.IMPOSSIBLE_REASON as c3_impossible_reason,
--   ctrl3month.IMPOSSIBLE_OTHER_REASON as c3_impossible_reason_other,  
--   ctrl3month.ABSCESS as c3_abscess, 
--   ctrl3month.ABSCESS_PAIN as c3_abscess_pain, 
--   ctrl3month.VASSCORE as c3_vasscore, 
--   ctrl3month.WORK as c3_work, 
--   ctrl3month.SORNESS as c3_soreness, 
--   ctrl3month.EMBARRESSED as c3_embarressed, 
--   ctrl3month.PREVENT_DAILY_WORK as c3_prevent_daily_work, 
--   ctrl3month.CLOTHING_OPTION as c3_clothing_option, 
--   ctrl3month.SOCIAL_LIFE as c3_social_life, 
--   ctrl3month.ATHLETIC_ACTIVITY as c3_athletic_activity, 
--   ctrl3month.PREVENT_WORK as c3_prevent_work, 
--   ctrl3month.WORK_PROBLEMS as c3_work_problems, 
--   ctrl3month.PARTNER_PROBLEMS as c3_parnter_problems, 
--   ctrl3month.SEXUAL_PROBLEMS as c3_sexual_problems, 
--   ctrl3month.PROBLEMS_LAST_WEEK as c3_problems_last_week, 
--   ctrl3month.DLQISUM as c3_dlqisum, 
--   ctrl3month.HURLEY_SCORE as c3_hurley_score, 
--   ctrl3month.RA as c3_ra, 
--   ctrl3month.RAN as c3_ran, 
--   ctrl3month.RAF as c3_raf, 
--   ctrl3month.RALD as c3_rald, 
--   ctrl3month.RAHUR as c3_rahur, 
--   ctrl3month.RG as c3_rg, 
--   ctrl3month.RGN as c3_rgn, 
--   ctrl3month.RGF as c3_rgf,
--   ctrl3month.RGLD as c3_rgld, 
--   ctrl3month.RGHUR as c3_rghur, 
--   ctrl3month.RGR as c3_rgr, 
--   ctrl3month.RGRN as c3_rgrn, 
--   ctrl3month.RGRF as c3_rgrf, 
--   ctrl3month.RGRLD as c3_rgrld, 
--   ctrl3month.RGRHUR as c3_rgrhur, 
--   ctrl3month.LA as c3_la, 
--   ctrl3month.LAN as c3_lan, 
--   ctrl3month.LAF as c3_laf, 
--   ctrl3month.LALD as c3_lald, 
--   ctrl3month.LAHUR as c3_lahur, 
--   ctrl3month.LG as c3_lg, 
--   ctrl3month.LGN as c3_lgn,
--   ctrl3month.LGF as c3_lgf,
--   ctrl3month.LGLD as c3_lgld, 
--   ctrl3month.LGHUR as c3_lghur,
--   ctrl3month.LGR as c3_lgr, 
--   ctrl3month.LGRN as c3_lgrn, 
--   ctrl3month.LGRF as c3_lgrf,
--   ctrl3month.LGRLD as c3_lgrld, 
--   ctrl3month.LGRHUR as c3_lgrhur, 
--   ctrl3month.OTHERREGION as c3_otherregion, 
--   ctrl3month.ORN as c3_orn, 
--   ctrl3month.ORF as c3_orf, 
--   ctrl3month.ORLD as c3_orld,
--   ctrl3month.ORHUR as c3_orhur,
--   ctrl3month.HSSCORESUM as c3_hsscoresum, 
--   ctrl3month.SURGERY_TYPE as c3_surgery_type, 
--   ctrl3month.AKSILLE as c3_aksille, 
--   ctrl3month.AKSILLE_RIGHT as c3_aksille_right, 
--   ctrl3month.AKSILLE_LEFT as c3_aksille_left, 
--   ctrl3month.AKSILLE_UNKNOWN as c3_aksille_unknown, 
--   ctrl3month.LYSKE as c3_lyske, 
--   ctrl3month.LYSKE_RIGHT as c3_lyske_right,  
--   ctrl3month.LYSKE_LEFT as c3_lyske_left,  
--   ctrl3month.LYSKE_UNKNOWN as c3_lyske_unknown,
--   ctrl3month.PUBIS as c3_pubis, 
--   ctrl3month.PUBIS_RIGHT as c3_pubis_right,  
--   ctrl3month.PUBIS_LEFT as c3_pubis_left, 
--   ctrl3month.PUBIS_CENTRAL as c3_pubis_central, 
--   ctrl3month.PUBIS_UNKNOWN as c3_pubis_unknown, 
--   ctrl3month.GENITALT as c3_genitalt, 
--   ctrl3month.GENITALT_RIGHT as c3_genitalt_right,  
--   ctrl3month.GENITALT_LEFT as c3_genitalt_left,   
--   ctrl3month.GENITALT_UNKNOWN as c3_genitalt_unknown,   
--   ctrl3month.PERIALT as c3_peritalt,  
--   ctrl3month.PERIALT_RIGHT as c3_peritalt_right, 
--   ctrl3month.PERIALT_LEFT as c3_peritalt_left, 
--   ctrl3month.PERIALT_UNKNOWN as c3_peritalt_unknown, 
--   ctrl3month.GLUTEALT as c3_glutealt, 
--   ctrl3month.GLUTEALT_RIGHT as c3_glutealt_right, 
--   ctrl3month.GLUTEALT_LEFT as c3_glutealt_left, 
--   ctrl3month.GLUTEALT_CENTRAL as c3_glutealt_central, 
--   ctrl3month.GLUTEALT_UNKNOWN as c3_glutealt_unknown, 
--   ctrl3month.MAMMAE as c3_mammae, 
--   ctrl3month.MAMMAE_RIGHT as c3_right, 
--   ctrl3month.MAMMAE_LEFT as c3_left, 
--   ctrl3month.MAMMAE_UNKNOWN as c3_unknown, 
--   ctrl3month.OTHER_LOCATION as c3_other_location, 
--   ctrl3month.OTHER_LOCATION_THIGHS as c3_other_location_thighs,  
--   ctrl3month.OTHER_LOCATION_STOMACH as c3_other_location_stomach,  
--   ctrl3month.OTHER_LOCATION_BACK as c3_other_location_back,  
--   ctrl3month.OTHER_LOCATION_NECK as c3_other_location_neck,  
--   ctrl3month.OTHER_LOCATION_OTHER as c3_other_location_other, 
--   ctrl3month.OTHER_LOCATION_OTHER_TEXT as c3_other_location_other_text,  
--   ctrl3month.INFECTION as c3_infection, 
--   ctrl3month.DELAYED_WOUND_HEALING as c3_delayed_wound_healing, 
--   ctrl3month.STRIKTURER as c3_stricturer,
--   ctrl3month.NERVEDAMAGE as c3_nervedamage, 
--   ctrl3month.BLOODPOISEN as c3_bloodpoisoning, 
--   ctrl3month.BLEEDING as c3_bleeding, 
--   ctrl3month.OTHER_COMPLICATIONS as c3_other_complications, 
--   ctrl3month.OTHER_COMPLICATIONS_TEXT as c3_other_complications_text,
--   ctrl3month.BIOLOGICAL_TREATMENT as c3_biological_treatment,  
--   ctrl3month.STOP_MEDICAL_TREATMENT as c3_medical_treatment, 
--   ctrl3month.SYSTEMIC_ANTIBIOTIC_THERAPY as c3_systemic_antibiotic_therapy, 
--   ctrl3month.SYSTEMIC_ANTIBIOTIC_THERAPY_STOP as c3_systemic_antibiotic_therapy_stop,  
--   ctrl3month.ANTIINFLAMMATORY_TREATMENT as c3_antiinflammatory_treatment, 
--   ctrl3month.ANTIINFLAMMATORY_TREATMENT_STOP as c3_antiinflammatory_treatment_stop, 
--   ctrl3month.ANALGESICS as c3_analgesics, 
--   ctrl3month.ANALGESICS_STOP as c3_analgesics_stop, 
--   ctrl3month.INTRALESIONAL_CORTICOSTEROID_INJECTION as c3_corticosteroid_injection, 
--   ctrl3month.INTRALESIONAL_CORTICOSTEROID_INJECTION_STOP as c3_corticosteroid_injection_stop, 
--   ctrl3month.ACELACIC_ACID as c3_acelacic_acid, 
--   ctrl3month.ACELACIC_ACID_STOP as c3_acelacic_acid_stop, 
--   ctrl3month.CLINDAMYCIN as c3_clindamycin, 
--   ctrl3month.CLINDAMYCIN_STOP as c3_clindamycin_stop, 
--   ctrl3month.RESORCINOL as c3_resorcinol, 
--   ctrl3month.RESORCINOL_STOP as c3_resorcinol_stop, 
--   ctrl3month.MEDICAL_INT_OTHER as c3_other_medication, 
--   ctrl3month.MEDICAL_INT_OTHER_STOP as c3_other_medication_stop, 
--   ctrl3month.HISCR_BOILS as c3_hiscr_boils,
--   ctrl3month.HISCR_INFLAMED as c3_hiscr_inflamed,
--   ctrl3month.HISCR_DRAINING as c3_hiscr_draining,     
--   ctrl3month.STATUS as c3_status,   
  
  ctrl6month.CENTREID as c6_centreid, 
--   ctrl6month.DO_MONTH as c6_do_month, 
  6 as c6_do_month, 
  ctrl6month.CONTROL_DATE as c6_date, 
--   ctrl6month.POSSIBLE as c6_possible,
  null as c6_possible,
--   ctrl6month.IMPOSSIBLE_REASON as c6_impossible_reason,
  null as c6_impossible_reason,
--   ctrl6month.IMPOSSIBLE_OTHER_REASON as c6_impossible_reason_other,  
  null as c6_impossible_reason_other,  
  ctrl6month.ABSCESS as c6_abscess, 
  ctrl6month.ABSCESS_PAIN as c6_abscess_pain, 
  ctrl6month.VASSCORE as c6_vasscore, 
  ctrl6month.WORK as c6_work, 
  ctrl6month.SORNESS as c6_soreness, 
  ctrl6month.EMBARRESSED as c6_embarressed, 
  ctrl6month.PREVENT_DAILY_WORK as c6_prevent_daily_work, 
  ctrl6month.CLOTHING_OPTION as c6_clothing_option, 
  ctrl6month.SOCIAL_LIFE as c6_social_life, 
  ctrl6month.ATHLETIC_ACTIVITY as c6_athletic_activity, 
  ctrl6month.PREVENT_WORK as c6_prevent_work, 
  ctrl6month.WORK_PROBLEMS as c6_work_problems, 
  ctrl6month.PARTNER_PROBLEMS as c6_parnter_problems, 
  ctrl6month.SEXUAL_PROBLEMS as c6_sexual_problems, 
  ctrl6month.PROBLEMS_LAST_WEEK as c6_problems_last_week, 
  ctrl6month.DLQISUM as c6_dlqisum, 
  ctrl6month.HURLEY_SCORE as c6_hurley_score, 
  ctrl6month.RA as c6_ra, 
  ctrl6month.RAN as c6_ran, 
  ctrl6month.RAF as c6_raf, 
  ctrl6month.RALD as c6_rald, 
  ctrl6month.RAHUR as c6_rahur, 
  ctrl6month.RG as c6_rg, 
  ctrl6month.RGN as c6_rgn, 
  ctrl6month.RGF as c6_rgf,
  ctrl6month.RGLD as c6_rgld, 
  ctrl6month.RGHUR as c6_rghur, 
  ctrl6month.RGR as c6_rgr, 
  ctrl6month.RGRN as c6_rgrn, 
  ctrl6month.RGRF as c6_rgrf, 
  ctrl6month.RGRLD as c6_rgrld, 
  ctrl6month.RGRHUR as c6_rgrhur, 
  ctrl6month.LA as c6_la, 
  ctrl6month.LAN as c6_lan, 
  ctrl6month.LAF as c6_laf, 
  ctrl6month.LALD as c6_lald, 
  ctrl6month.LAHUR as c6_lahur, 
  ctrl6month.LG as c6_lg, 
  ctrl6month.LGN as c6_lgn,
  ctrl6month.LGF as c6_lgf,
  ctrl6month.LGLD as c6_lgld, 
  ctrl6month.LGHUR as c6_lghur,
  ctrl6month.LGR as c6_lgr, 
  ctrl6month.LGRN as c6_lgrn, 
  ctrl6month.LGRF as c6_lgrf,
  ctrl6month.LGRLD as c6_lgrld, 
  ctrl6month.LGRHUR as c6_lgrhur, 
  ctrl6month.OTHERREGION as c6_otherregion, 
  ctrl6month.ORN as c6_orn, 
  ctrl6month.ORF as c6_orf, 
  ctrl6month.ORLD as c6_orld,
  ctrl6month.ORHUR as c6_orhur,
  ctrl6month.HSSCORESUM as c6_hsscoresum, 
  ctrl6month.SURGERY_TYPE as c6_surgery_type, 
  ctrl6month.AKSILLE as c6_aksille, 
  ctrl6month.AKSILLE_RIGHT as c6_aksille_right, 
  ctrl6month.AKSILLE_LEFT as c6_aksille_left, 
  ctrl6month.AKSILLE_UNKNOWN as c6_aksille_unknown, 
  ctrl6month.LYSKE as c6_lyske, 
  ctrl6month.LYSKE_RIGHT as c6_lyske_right,  
  ctrl6month.LYSKE_LEFT as c6_lyske_left,  
  ctrl6month.LYSKE_UNKNOWN as c6_lyske_unknown,
  ctrl6month.PUBIS as c6_pubis, 
  ctrl6month.PUBIS_RIGHT as c6_pubis_right,  
  ctrl6month.PUBIS_LEFT as c6_pubis_left, 
  ctrl6month.PUBIS_CENTRAL as c6_pubis_central, 
  ctrl6month.PUBIS_UNKNOWN as c6_pubis_unknown, 
  ctrl6month.GENITALT as c6_genitalt, 
  ctrl6month.GENITALT_RIGHT as c6_genitalt_right,  
  ctrl6month.GENITALT_LEFT as c6_genitalt_left,   
  ctrl6month.GENITALT_UNKNOWN as c6_genitalt_unknown,   
  ctrl6month.PERIALT as c6_peritalt,  
  ctrl6month.PERIALT_RIGHT as c6_peritalt_right, 
  ctrl6month.PERIALT_LEFT as c6_peritalt_left, 
  ctrl6month.PERIALT_UNKNOWN as c6_peritalt_unknown, 
  ctrl6month.GLUTEALT as c6_glutealt, 
  ctrl6month.GLUTEALT_RIGHT as c6_glutealt_right, 
  ctrl6month.GLUTEALT_LEFT as c6_glutealt_left, 
  ctrl6month.GLUTEALT_CENTRAL as c6_glutealt_central, 
  ctrl6month.GLUTEALT_UNKNOWN as c6_glutealt_unknown, 
  ctrl6month.MAMMAE as c6_mammae, 
  ctrl6month.MAMMAE_RIGHT as c6_right, 
  ctrl6month.MAMMAE_LEFT as c6_left, 
  ctrl6month.MAMMAE_UNKNOWN as c6_unknown, 
  ctrl6month.OTHER_LOCATION as c6_other_location, 
  ctrl6month.OTHER_LOCATION_THIGHS as c6_other_location_thighs,  
  ctrl6month.OTHER_LOCATION_STOMACH as c6_other_location_stomach,  
  ctrl6month.OTHER_LOCATION_BACK as c6_other_location_back,  
  ctrl6month.OTHER_LOCATION_NECK as c6_other_location_neck,  
  ctrl6month.OTHER_LOCATION_OTHER as c6_other_location_other, 
  ctrl6month.OTHER_LOCATION_OTHER_TEXT as c6_other_location_other_text,  
  ctrl6month.INFECTION as c6_infection, 
  ctrl6month.DELAYED_WOUND_HEALING as c6_delayed_wound_healing, 
  ctrl6month.STRIKTURER as c6_stricturer,
  ctrl6month.NERVEDAMAGE as c6_nervedamage, 
  ctrl6month.BLOODPOISEN as c6_bloodpoisoning, 
  ctrl6month.BLEEDING as c6_bleeding, 
  ctrl6month.OTHER_COMPLICATIONS as c6_other_complications, 
  ctrl6month.OTHER_COMPLICATIONS_TEXT as c6_other_complications_text,
  ctrl6month.BIOLOGICAL_TREATMENT as c6_biological_treatment,  
  ctrl6month.STOP_MEDICAL_TREATMENT as c6_medical_treatment, 
  ctrl6month.SYSTEMIC_ANTIBIOTIC_THERAPY as c6_systemic_antibiotic_therapy, 
  ctrl6month.SYSTEMIC_ANTIBIOTIC_THERAPY_STOP as c6_systemic_antibiotic_therapy_stop,  
  ctrl6month.ANTIINFLAMMATORY_TREATMENT as c6_antiinflammatory_treatment, 
  ctrl6month.ANTIINFLAMMATORY_TREATMENT_STOP as c6_antiinflammatory_treatment_stop, 
  ctrl6month.ANALGESICS as c6_analgesics, 
  ctrl6month.ANALGESICS_STOP as c6_analgesics_stop, 
--   ctrl6month.INTRALESIONAL_CORTICOSTEROID_INJECTION as c6_corticosteroid_injection, 
  null as c6_corticosteroid_injection, 
--   ctrl6month.INTRALESIONAL_CORTICOSTEROID_INJECTION_STOP as c6_corticosteroid_injection_stop, 
  null as c6_corticosteroid_injection_stop, 
--   ctrl6month.ACELACIC_ACID as c6_acelacic_acid, 
  null as c6_acelacic_acid, 
--   ctrl6month.ACELACIC_ACID_STOP as c6_acelacic_acid_stop, 
  null as c6_acelacic_acid_stop, 
--   ctrl6month.CLINDAMYCIN as c6_clindamycin, 
  null as c6_clindamycin, 
--   ctrl6month.CLINDAMYCIN_STOP as c6_clindamycin_stop, 
  null as c6_clindamycin_stop, 
--   ctrl6month.RESORCINOL as c6_resorcinol, 
  null as c6_resorcinol, 
--   ctrl6month.RESORCINOL_STOP as c6_resorcinol_stop, 
  null as c6_resorcinol_stop, 
--   ctrl6month.MEDICAL_INT_OTHER as c6_other_medication, 
  null as c6_other_medication, 
--   ctrl6month.MEDICAL_INT_OTHER_STOP as c6_other_medication_stop, 
  null as c6_other_medication_stop, 
--   ctrl6month.HISCR_BOILS as c6_hiscr_boils,
  null as c6_hiscr_boils,
--   ctrl6month.HISCR_INFLAMED as c6_hiscr_inflamed,
  null as c6_hiscr_inflamed,
--   ctrl6month.HISCR_DRAINING as c6_hiscr_draining,    
  null as c6_hiscr_draining,    
  ctrl6month.STATUS as c6_status
-- ,  
--   ctrl9month.CENTREID as c9_centreid, 
--   ctrl9month.DO_MONTH as c9_do_month, 
--   ctrl9month.CONTROL_DATE as c9_date, 
--   ctrl9month.POSSIBLE as c9_possible,
--   ctrl9month.IMPOSSIBLE_REASON as c9_impossible_reason,
--   ctrl9month.IMPOSSIBLE_OTHER_REASON as c9_impossible_reason_other,  
--   ctrl9month.ABSCESS as c9_abscess, 
--   ctrl9month.ABSCESS_PAIN as c9_abscess_pain, 
--   ctrl9month.VASSCORE as c9_vasscore, 
--   ctrl9month.WORK as c9_work, 
--   ctrl9month.SORNESS as c9_soreness, 
--   ctrl9month.EMBARRESSED as c9_embarressed, 
--   ctrl9month.PREVENT_DAILY_WORK as c9_prevent_daily_work, 
--   ctrl9month.CLOTHING_OPTION as c9_clothing_option, 
--   ctrl9month.SOCIAL_LIFE as c9_social_life, 
--   ctrl9month.ATHLETIC_ACTIVITY as c9_athletic_activity, 
--   ctrl9month.PREVENT_WORK as c9_prevent_work, 
--   ctrl9month.WORK_PROBLEMS as c9_work_problems, 
--   ctrl9month.PARTNER_PROBLEMS as c9_parnter_problems, 
--   ctrl9month.SEXUAL_PROBLEMS as c9_sexual_problems, 
--   ctrl9month.PROBLEMS_LAST_WEEK as c9_problems_last_week, 
--   ctrl9month.DLQISUM as c9_dlqisum, 
--   ctrl9month.HURLEY_SCORE as c9_hurley_score, 
--   ctrl9month.RA as c9_ra, 
--   ctrl9month.RAN as c9_ran, 
--   ctrl9month.RAF as c9_raf, 
--   ctrl9month.RALD as c9_rald, 
--   ctrl9month.RAHUR as c9_rahur, 
--   ctrl9month.RG as c9_rg, 
--   ctrl9month.RGN as c9_rgn, 
--   ctrl9month.RGF as c9_rgf,
--   ctrl9month.RGLD as c9_rgld, 
--   ctrl9month.RGHUR as c9_rghur, 
--   ctrl9month.RGR as c9_rgr, 
--   ctrl9month.RGRN as c9_rgrn, 
--   ctrl9month.RGRF as c9_rgrf, 
--   ctrl9month.RGRLD as c9_rgrld, 
--   ctrl9month.RGRHUR as c9_rgrhur, 
--   ctrl9month.LA as c9_la, 
--   ctrl9month.LAN as c9_lan, 
--   ctrl9month.LAF as c9_laf, 
--   ctrl9month.LALD as c9_lald, 
--   ctrl9month.LAHUR as c9_lahur, 
--   ctrl9month.LG as c9_lg, 
--   ctrl9month.LGN as c9_lgn,
--   ctrl9month.LGF as c9_lgf,
--   ctrl9month.LGLD as c9_lgld, 
--   ctrl9month.LGHUR as c9_lghur,
--   ctrl9month.LGR as c9_lgr, 
--   ctrl9month.LGRN as c9_lgrn, 
--   ctrl9month.LGRF as c9_lgrf,
--   ctrl9month.LGRLD as c9_lgrld, 
--   ctrl9month.LGRHUR as c9_lgrhur, 
--   ctrl9month.OTHERREGION as c9_otherregion, 
--   ctrl9month.ORN as c9_orn, 
--   ctrl9month.ORF as c9_orf, 
--   ctrl9month.ORLD as c9_orld,
--   ctrl9month.ORHUR as c9_orhur,
--   ctrl9month.HSSCORESUM as c9_hsscoresum, 
--   ctrl9month.SURGERY_TYPE as c9_surgery_type, 
--   ctrl9month.AKSILLE as c9_aksille, 
--   ctrl9month.AKSILLE_RIGHT as c9_aksille_right, 
--   ctrl9month.AKSILLE_LEFT as c9_aksille_left, 
--   ctrl9month.AKSILLE_UNKNOWN as c9_aksille_unknown, 
--   ctrl9month.LYSKE as c9_lyske, 
--   ctrl9month.LYSKE_RIGHT as c9_lyske_right,  
--   ctrl9month.LYSKE_LEFT as c9_lyske_left,  
--   ctrl9month.LYSKE_UNKNOWN as c9_lyske_unknown,
--   ctrl9month.PUBIS as c9_pubis, 
--   ctrl9month.PUBIS_RIGHT as c9_pubis_right,  
--   ctrl9month.PUBIS_LEFT as c9_pubis_left, 
--   ctrl9month.PUBIS_CENTRAL as c9_pubis_central, 
--   ctrl9month.PUBIS_UNKNOWN as c9_pubis_unknown, 
--   ctrl9month.GENITALT as c9_genitalt, 
--   ctrl9month.GENITALT_RIGHT as c9_genitalt_right,  
--   ctrl9month.GENITALT_LEFT as c9_genitalt_left,   
--   ctrl9month.GENITALT_UNKNOWN as c9_genitalt_unknown,   
--   ctrl9month.PERIALT as c9_peritalt,  
--   ctrl9month.PERIALT_RIGHT as c9_peritalt_right, 
--   ctrl9month.PERIALT_LEFT as c9_peritalt_left, 
--   ctrl9month.PERIALT_UNKNOWN as c9_peritalt_unknown, 
--   ctrl9month.GLUTEALT as c9_glutealt, 
--   ctrl9month.GLUTEALT_RIGHT as c9_glutealt_right, 
--   ctrl9month.GLUTEALT_LEFT as c9_glutealt_left, 
--   ctrl9month.GLUTEALT_CENTRAL as c9_glutealt_central, 
--   ctrl9month.GLUTEALT_UNKNOWN as c9_glutealt_unknown, 
--   ctrl9month.MAMMAE as c9_mammae, 
--   ctrl9month.MAMMAE_RIGHT as c9_right, 
--   ctrl9month.MAMMAE_LEFT as c9_left, 
--   ctrl9month.MAMMAE_UNKNOWN as c9_unknown, 
--   ctrl9month.OTHER_LOCATION as c9_other_location, 
--   ctrl9month.OTHER_LOCATION_THIGHS as c9_other_location_thighs,  
--   ctrl9month.OTHER_LOCATION_STOMACH as c9_other_location_stomach,  
--   ctrl9month.OTHER_LOCATION_BACK as c9_other_location_back,  
--   ctrl9month.OTHER_LOCATION_NECK as c9_other_location_neck,  
--   ctrl9month.OTHER_LOCATION_OTHER as c9_other_location_other, 
--   ctrl9month.OTHER_LOCATION_OTHER_TEXT as c9_other_location_other_text,  
--   ctrl9month.INFECTION as c9_infection, 
--   ctrl9month.DELAYED_WOUND_HEALING as c9_delayed_wound_healing, 
--   ctrl9month.STRIKTURER as c9_stricturer,
--   ctrl9month.NERVEDAMAGE as c9_nervedamage, 
--   ctrl9month.BLOODPOISEN as c9_bloodpoisoning, 
--   ctrl9month.BLEEDING as c9_bleeding, 
--   ctrl9month.OTHER_COMPLICATIONS as c9_other_complications, 
--   ctrl9month.OTHER_COMPLICATIONS_TEXT as c9_other_complications_text,
--   ctrl9month.BIOLOGICAL_TREATMENT as c9_biological_treatment,  
--   ctrl9month.STOP_MEDICAL_TREATMENT as c9_medical_treatment, 
--   ctrl9month.SYSTEMIC_ANTIBIOTIC_THERAPY as c9_systemic_antibiotic_therapy, 
--   ctrl9month.SYSTEMIC_ANTIBIOTIC_THERAPY_STOP as c9_systemic_antibiotic_therapy_stop,  
--   ctrl9month.ANTIINFLAMMATORY_TREATMENT as c9_antiinflammatory_treatment, 
--   ctrl9month.ANTIINFLAMMATORY_TREATMENT_STOP as c9_antiinflammatory_treatment_stop, 
--   ctrl9month.ANALGESICS as c9_analgesics, 
--   ctrl9month.ANALGESICS_STOP as c9_analgesics_stop, 
--   ctrl9month.INTRALESIONAL_CORTICOSTEROID_INJECTION as c9_corticosteroid_injection, 
--   ctrl9month.INTRALESIONAL_CORTICOSTEROID_INJECTION_STOP as c9_corticosteroid_injection_stop, 
--   ctrl9month.ACELACIC_ACID as c9_acelacic_acid, 
--   ctrl9month.ACELACIC_ACID_STOP as c9_acelacic_acid_stop, 
--   ctrl9month.CLINDAMYCIN as c9_clindamycin, 
--   ctrl9month.CLINDAMYCIN_STOP as c9_clindamycin_stop, 
--   ctrl9month.RESORCINOL as c9_resorcinol, 
--   ctrl9month.RESORCINOL_STOP as c9_resorcinol_stop, 
--   ctrl9month.MEDICAL_INT_OTHER as c9_other_medication, 
--   ctrl9month.MEDICAL_INT_OTHER_STOP as c9_other_medication_stop, 
--   ctrl9month.HISCR_BOILS as c9_hiscr_boils,
--   ctrl9month.HISCR_INFLAMED as c9_hiscr_inflamed,
--   ctrl9month.HISCR_DRAINING as c9_hiscr_draining,     
--   ctrl9month.STATUS as c9_status, 
--   
--     ctrl12month.CENTREID as c12_centreid, 
--   ctrl12month.DO_MONTH as c12_do_month, 
--   ctrl12month.CONTROL_DATE as c12_date, 
--   ctrl12month.POSSIBLE as c12_possible,
--   ctrl12month.IMPOSSIBLE_REASON as c12_impossible_reason,
--   ctrl12month.IMPOSSIBLE_OTHER_REASON as c12_impossible_reason_other,  
--   ctrl12month.ABSCESS as c12_abscess, 
--   ctrl12month.ABSCESS_PAIN as c12_abscess_pain, 
--   ctrl12month.VASSCORE as c12_vasscore, 
--   ctrl12month.WORK as c12_work, 
--   ctrl12month.SORNESS as c12_soreness, 
--   ctrl12month.EMBARRESSED as c12_embarressed, 
--   ctrl12month.PREVENT_DAILY_WORK as c12_prevent_daily_work, 
--   ctrl12month.CLOTHING_OPTION as c12_clothing_option, 
--   ctrl12month.SOCIAL_LIFE as c12_social_life, 
--   ctrl12month.ATHLETIC_ACTIVITY as c12_athletic_activity, 
--   ctrl12month.PREVENT_WORK as c12_prevent_work, 
--   ctrl12month.WORK_PROBLEMS as c12_work_problems, 
--   ctrl12month.PARTNER_PROBLEMS as c12_parnter_problems, 
--   ctrl12month.SEXUAL_PROBLEMS as c12_sexual_problems, 
--   ctrl12month.PROBLEMS_LAST_WEEK as c12_problems_last_week, 
--   ctrl12month.DLQISUM as c12_dlqisum, 
--   ctrl12month.HURLEY_SCORE as c12_hurley_score, 
--   ctrl12month.RA as c12_ra, 
--   ctrl12month.RAN as c12_ran, 
--   ctrl12month.RAF as c12_raf, 
--   ctrl12month.RALD as c12_rald, 
--   ctrl12month.RAHUR as c12_rahur, 
--   ctrl12month.RG as c12_rg, 
--   ctrl12month.RGN as c12_rgn, 
--   ctrl12month.RGF as c12_rgf,
--   ctrl12month.RGLD as c12_rgld, 
--   ctrl12month.RGHUR as c12_rghur, 
--   ctrl12month.RGR as c12_rgr, 
--   ctrl12month.RGRN as c12_rgrn, 
--   ctrl12month.RGRF as c12_rgrf, 
--   ctrl12month.RGRLD as c12_rgrld, 
--   ctrl12month.RGRHUR as c12_rgrhur, 
--   ctrl12month.LA as c12_la, 
--   ctrl12month.LAN as c12_lan, 
--   ctrl12month.LAF as c12_laf, 
--   ctrl12month.LALD as c12_lald, 
--   ctrl12month.LAHUR as c12_lahur, 
--   ctrl12month.LG as c12_lg, 
--   ctrl12month.LGN as c12_lgn,
--   ctrl12month.LGF as c12_lgf,
--   ctrl12month.LGLD as c12_lgld, 
--   ctrl12month.LGHUR as c12_lghur,
--   ctrl12month.LGR as c12_lgr, 
--   ctrl12month.LGRN as c12_lgrn, 
--   ctrl12month.LGRF as c12_lgrf,
--   ctrl12month.LGRLD as c12_lgrld, 
--   ctrl12month.LGRHUR as c12_lgrhur, 
--   ctrl12month.OTHERREGION as c12_otherregion, 
--   ctrl12month.ORN as c12_orn, 
--   ctrl12month.ORF as c12_orf, 
--   ctrl12month.ORLD as c12_orld,
--   ctrl12month.ORHUR as c12_orhur,
--   ctrl12month.HSSCORESUM as c12_hsscoresum, 
--   ctrl12month.SURGERY_TYPE as c12_surgery_type, 
--   ctrl12month.AKSILLE as c12_aksille, 
--   ctrl12month.AKSILLE_RIGHT as c12_aksille_right, 
--   ctrl12month.AKSILLE_LEFT as c12_aksille_left, 
--   ctrl12month.AKSILLE_UNKNOWN as c12_aksille_unknown, 
--   ctrl12month.LYSKE as c12_lyske, 
--   ctrl12month.LYSKE_RIGHT as c12_lyske_right,  
--   ctrl12month.LYSKE_LEFT as c12_lyske_left,  
--   ctrl12month.LYSKE_UNKNOWN as c12_lyske_unknown,
--   ctrl12month.PUBIS as c12_pubis, 
--   ctrl12month.PUBIS_RIGHT as c12_pubis_right,  
--   ctrl12month.PUBIS_LEFT as c12_pubis_left, 
--   ctrl12month.PUBIS_CENTRAL as c12_pubis_central, 
--   ctrl12month.PUBIS_UNKNOWN as c12_pubis_unknown, 
--   ctrl12month.GENITALT as c12_genitalt, 
--   ctrl12month.GENITALT_RIGHT as c12_genitalt_right,  
--   ctrl12month.GENITALT_LEFT as c12_genitalt_left,   
--   ctrl12month.GENITALT_UNKNOWN as c12_genitalt_unknown,   
--   ctrl12month.PERIALT as c12_peritalt,  
--   ctrl12month.PERIALT_RIGHT as c12_peritalt_right, 
--   ctrl12month.PERIALT_LEFT as c12_peritalt_left, 
--   ctrl12month.PERIALT_UNKNOWN as c12_peritalt_unknown, 
--   ctrl12month.GLUTEALT as c12_glutealt, 
--   ctrl12month.GLUTEALT_RIGHT as c12_glutealt_right, 
--   ctrl12month.GLUTEALT_LEFT as c12_glutealt_left, 
--   ctrl12month.GLUTEALT_CENTRAL as c12_glutealt_central, 
--   ctrl12month.GLUTEALT_UNKNOWN as c12_glutealt_unknown, 
--   ctrl12month.MAMMAE as c12_mammae, 
--   ctrl12month.MAMMAE_RIGHT as c12_right, 
--   ctrl12month.MAMMAE_LEFT as c12_left, 
--   ctrl12month.MAMMAE_UNKNOWN as c12_unknown, 
--   ctrl12month.OTHER_LOCATION as c12_other_location, 
--   ctrl12month.OTHER_LOCATION_THIGHS as c12_other_location_thighs,  
--   ctrl12month.OTHER_LOCATION_STOMACH as c12_other_location_stomach,  
--   ctrl12month.OTHER_LOCATION_BACK as c12_other_location_back,  
--   ctrl12month.OTHER_LOCATION_NECK as c12_other_location_neck,  
--   ctrl12month.OTHER_LOCATION_OTHER as c12_other_location_other, 
--   ctrl12month.OTHER_LOCATION_OTHER_TEXT as c12_other_location_other_text,  
--   ctrl12month.INFECTION as c12_infection, 
--   ctrl12month.DELAYED_WOUND_HEALING as c12_delayed_wound_healing, 
--   ctrl12month.STRIKTURER as c12_stricturer,
--   ctrl12month.NERVEDAMAGE as c12_nervedamage, 
--   ctrl12month.BLOODPOISEN as c12_bloodpoisoning, 
--   ctrl12month.BLEEDING as c12_bleeding, 
--   ctrl12month.OTHER_COMPLICATIONS as c12_other_complications, 
--   ctrl12month.OTHER_COMPLICATIONS_TEXT as c12_other_complications_text,
--   ctrl12month.BIOLOGICAL_TREATMENT as c12_biological_treatment,  
--   ctrl12month.STOP_MEDICAL_TREATMENT as c12_medical_treatment, 
--   ctrl12month.SYSTEMIC_ANTIBIOTIC_THERAPY as c12_systemic_antibiotic_therapy, 
--   ctrl12month.SYSTEMIC_ANTIBIOTIC_THERAPY_STOP as c12_systemic_antibiotic_therapy_stop,  
--   ctrl12month.ANTIINFLAMMATORY_TREATMENT as c12_antiinflammatory_treatment, 
--   ctrl12month.ANTIINFLAMMATORY_TREATMENT_STOP as c12_antiinflammatory_treatment_stop, 
--   ctrl12month.ANALGESICS as c12_analgesics, 
--   ctrl12month.ANALGESICS_STOP as c12_analgesics_stop, 
--   ctrl12month.INTRALESIONAL_CORTICOSTEROID_INJECTION as c12_corticosteroid_injection, 
--   ctrl12month.INTRALESIONAL_CORTICOSTEROID_INJECTION_STOP as c12_corticosteroid_injection_stop, 
--   ctrl12month.ACELACIC_ACID as c12_acelacic_acid, 
--   ctrl12month.ACELACIC_ACID_STOP as c12_acelacic_acid_stop, 
--   ctrl12month.CLINDAMYCIN as c12_clindamycin, 
--   ctrl12month.CLINDAMYCIN_STOP as c12_clindamycin_stop, 
--   ctrl12month.RESORCINOL as c12_resorcinol, 
--   ctrl12month.RESORCINOL_STOP as c12_resorcinol_stop, 
--   ctrl12month.MEDICAL_INT_OTHER as c12_other_medication, 
--   ctrl12month.MEDICAL_INT_OTHER_STOP as c12_other_medication_stop, 
--   ctrl12month.HISCR_BOILS as c12_hiscr_boils,
--   ctrl12month.HISCR_INFLAMED as c12_hiscr_inflamed,
--   ctrl12month.HISCR_DRAINING as c12_hiscr_draining,     
--   ctrl12month.STATUS as c12_status, 
--   
--   ctrl15month.CENTREID as c15_centreid, 
--   ctrl15month.DO_MONTH as c15_do_month, 
--   ctrl15month.CONTROL_DATE as c15_date, 
--   ctrl15month.POSSIBLE as c15_possible,
--   ctrl15month.IMPOSSIBLE_REASON as c15_impossible_reason,
--   ctrl15month.IMPOSSIBLE_OTHER_REASON as c15_impossible_reason_other,  
--   ctrl15month.ABSCESS as c15_abscess, 
--   ctrl15month.ABSCESS_PAIN as c15_abscess_pain, 
--   ctrl15month.VASSCORE as c15_vasscore, 
--   ctrl15month.WORK as c15_work, 
--   ctrl15month.SORNESS as c15_soreness, 
--   ctrl15month.EMBARRESSED as c15_embarressed, 
--   ctrl15month.PREVENT_DAILY_WORK as c15_prevent_daily_work, 
--   ctrl15month.CLOTHING_OPTION as c15_clothing_option, 
--   ctrl15month.SOCIAL_LIFE as c15_social_life, 
--   ctrl15month.ATHLETIC_ACTIVITY as c15_athletic_activity, 
--   ctrl15month.PREVENT_WORK as c15_prevent_work, 
--   ctrl15month.WORK_PROBLEMS as c15_work_problems, 
--   ctrl15month.PARTNER_PROBLEMS as c15_parnter_problems, 
--   ctrl15month.SEXUAL_PROBLEMS as c15_sexual_problems, 
--   ctrl15month.PROBLEMS_LAST_WEEK as c15_problems_last_week, 
--   ctrl15month.DLQISUM as c15_dlqisum, 
--   ctrl15month.HURLEY_SCORE as c15_hurley_score, 
--   ctrl15month.RA as c15_ra, 
--   ctrl15month.RAN as c15_ran, 
--   ctrl15month.RAF as c15_raf, 
--   ctrl15month.RALD as c15_rald, 
--   ctrl15month.RAHUR as c15_rahur, 
--   ctrl15month.RG as c15_rg, 
--   ctrl15month.RGN as c15_rgn, 
--   ctrl15month.RGF as c15_rgf,
--   ctrl15month.RGLD as c15_rgld, 
--   ctrl15month.RGHUR as c15_rghur, 
--   ctrl15month.RGR as c15_rgr, 
--   ctrl15month.RGRN as c15_rgrn, 
--   ctrl15month.RGRF as c15_rgrf, 
--   ctrl15month.RGRLD as c15_rgrld, 
--   ctrl15month.RGRHUR as c15_rgrhur, 
--   ctrl15month.LA as c15_la, 
--   ctrl15month.LAN as c15_lan, 
--   ctrl15month.LAF as c15_laf, 
--   ctrl15month.LALD as c15_lald, 
--   ctrl15month.LAHUR as c15_lahur, 
--   ctrl15month.LG as c15_lg, 
--   ctrl15month.LGN as c15_lgn,
--   ctrl15month.LGF as c15_lgf,
--   ctrl15month.LGLD as c15_lgld, 
--   ctrl15month.LGHUR as c15_lghur,
--   ctrl15month.LGR as c15_lgr, 
--   ctrl15month.LGRN as c15_lgrn, 
--   ctrl15month.LGRF as c15_lgrf,
--   ctrl15month.LGRLD as c15_lgrld, 
--   ctrl15month.LGRHUR as c15_lgrhur, 
--   ctrl15month.OTHERREGION as c15_otherregion, 
--   ctrl15month.ORN as c15_orn, 
--   ctrl15month.ORF as c15_orf, 
--   ctrl15month.ORLD as c15_orld,
--   ctrl15month.ORHUR as c15_orhur,
--   ctrl15month.HSSCORESUM as c15_hsscoresum, 
--   ctrl15month.SURGERY_TYPE as c15_surgery_type, 
--   ctrl15month.AKSILLE as c15_aksille, 
--   ctrl15month.AKSILLE_RIGHT as c15_aksille_right, 
--   ctrl15month.AKSILLE_LEFT as c15_aksille_left, 
--   ctrl15month.AKSILLE_UNKNOWN as c15_aksille_unknown, 
--   ctrl15month.LYSKE as c15_lyske, 
--   ctrl15month.LYSKE_RIGHT as c15_lyske_right,  
--   ctrl15month.LYSKE_LEFT as c15_lyske_left,  
--   ctrl15month.LYSKE_UNKNOWN as c15_lyske_unknown,
--   ctrl15month.PUBIS as c15_pubis, 
--   ctrl15month.PUBIS_RIGHT as c15_pubis_right,  
--   ctrl15month.PUBIS_LEFT as c15_pubis_left, 
--   ctrl15month.PUBIS_CENTRAL as c15_pubis_central, 
--   ctrl15month.PUBIS_UNKNOWN as c15_pubis_unknown, 
--   ctrl15month.GENITALT as c15_genitalt, 
--   ctrl15month.GENITALT_RIGHT as c15_genitalt_right,  
--   ctrl15month.GENITALT_LEFT as c15_genitalt_left,   
--   ctrl15month.GENITALT_UNKNOWN as c15_genitalt_unknown,   
--   ctrl15month.PERIALT as c15_peritalt,  
--   ctrl15month.PERIALT_RIGHT as c15_peritalt_right, 
--   ctrl15month.PERIALT_LEFT as c15_peritalt_left, 
--   ctrl15month.PERIALT_UNKNOWN as c15_peritalt_unknown, 
--   ctrl15month.GLUTEALT as c15_glutealt, 
--   ctrl15month.GLUTEALT_RIGHT as c15_glutealt_right, 
--   ctrl15month.GLUTEALT_LEFT as c15_glutealt_left, 
--   ctrl15month.GLUTEALT_CENTRAL as c15_glutealt_central, 
--   ctrl15month.GLUTEALT_UNKNOWN as c15_glutealt_unknown, 
--   ctrl15month.MAMMAE as c15_mammae, 
--   ctrl15month.MAMMAE_RIGHT as c15_right, 
--   ctrl15month.MAMMAE_LEFT as c15_left, 
--   ctrl15month.MAMMAE_UNKNOWN as c15_unknown, 
--   ctrl15month.OTHER_LOCATION as c15_other_location, 
--   ctrl15month.OTHER_LOCATION_THIGHS as c15_other_location_thighs,  
--   ctrl15month.OTHER_LOCATION_STOMACH as c15_other_location_stomach,  
--   ctrl15month.OTHER_LOCATION_BACK as c15_other_location_back,  
--   ctrl15month.OTHER_LOCATION_NECK as c15_other_location_neck,  
--   ctrl15month.OTHER_LOCATION_OTHER as c15_other_location_other, 
--   ctrl15month.OTHER_LOCATION_OTHER_TEXT as c15_other_location_other_text,  
--   ctrl15month.INFECTION as c15_infection, 
--   ctrl15month.DELAYED_WOUND_HEALING as c15_delayed_wound_healing, 
--   ctrl15month.STRIKTURER as c15_stricturer,
--   ctrl15month.NERVEDAMAGE as c15_nervedamage, 
--   ctrl15month.BLOODPOISEN as c15_bloodpoisoning, 
--   ctrl15month.BLEEDING as c15_bleeding, 
--   ctrl15month.OTHER_COMPLICATIONS as c15_other_complications, 
--   ctrl15month.OTHER_COMPLICATIONS_TEXT as c15_other_complications_text,
--   ctrl15month.BIOLOGICAL_TREATMENT as c15_biological_treatment,  
--   ctrl15month.STOP_MEDICAL_TREATMENT as c15_medical_treatment, 
--   ctrl15month.SYSTEMIC_ANTIBIOTIC_THERAPY as c15_systemic_antibiotic_therapy, 
--   ctrl15month.SYSTEMIC_ANTIBIOTIC_THERAPY_STOP as c15_systemic_antibiotic_therapy_stop,  
--   ctrl15month.ANTIINFLAMMATORY_TREATMENT as c15_antiinflammatory_treatment, 
--   ctrl15month.ANTIINFLAMMATORY_TREATMENT_STOP as c15_antiinflammatory_treatment_stop, 
--   ctrl15month.ANALGESICS as c15_analgesics, 
--   ctrl15month.ANALGESICS_STOP as c15_analgesics_stop, 
--   ctrl15month.INTRALESIONAL_CORTICOSTEROID_INJECTION as c15_corticosteroid_injection, 
--   ctrl15month.INTRALESIONAL_CORTICOSTEROID_INJECTION_STOP as c15_corticosteroid_injection_stop, 
--   ctrl15month.ACELACIC_ACID as c15_acelacic_acid, 
--   ctrl15month.ACELACIC_ACID_STOP as c15_acelacic_acid_stop, 
--   ctrl15month.CLINDAMYCIN as c15_clindamycin, 
--   ctrl15month.CLINDAMYCIN_STOP as c15_clindamycin_stop, 
--   ctrl15month.RESORCINOL as c15_resorcinol, 
--   ctrl15month.RESORCINOL_STOP as c15_resorcinol_stop, 
--   ctrl15month.MEDICAL_INT_OTHER as c15_other_medication, 
--   ctrl15month.MEDICAL_INT_OTHER_STOP as c15_other_medication_stop, 
--   ctrl15month.HISCR_BOILS as c15_hiscr_boils,
--   ctrl15month.HISCR_INFLAMED as c15_hiscr_inflamed,
--   ctrl15month.HISCR_DRAINING as c15_hiscr_draining,     
--   ctrl15month.STATUS as c15_status, 
--   
--     ctrl18month.CENTREID as c18_centreid, 
--   ctrl18month.DO_MONTH as c18_do_month, 
--   ctrl18month.CONTROL_DATE as c18_date, 
--   ctrl18month.POSSIBLE as c18_possible,
--   ctrl18month.IMPOSSIBLE_REASON as c18_impossible_reason,
--   ctrl18month.IMPOSSIBLE_OTHER_REASON as c18_impossible_reason_other,  
--   ctrl18month.ABSCESS as c18_abscess, 
--   ctrl18month.ABSCESS_PAIN as c18_abscess_pain, 
--   ctrl18month.VASSCORE as c18_vasscore, 
--   ctrl18month.WORK as c18_work, 
--   ctrl18month.SORNESS as c18_soreness, 
--   ctrl18month.EMBARRESSED as c18_embarressed, 
--   ctrl18month.PREVENT_DAILY_WORK as c18_prevent_daily_work, 
--   ctrl18month.CLOTHING_OPTION as c18_clothing_option, 
--   ctrl18month.SOCIAL_LIFE as c18_social_life, 
--   ctrl18month.ATHLETIC_ACTIVITY as c18_athletic_activity, 
--   ctrl18month.PREVENT_WORK as c18_prevent_work, 
--   ctrl18month.WORK_PROBLEMS as c18_work_problems, 
--   ctrl18month.PARTNER_PROBLEMS as c18_parnter_problems, 
--   ctrl18month.SEXUAL_PROBLEMS as c18_sexual_problems, 
--   ctrl18month.PROBLEMS_LAST_WEEK as c18_problems_last_week, 
--   ctrl18month.DLQISUM as c18_dlqisum, 
--   ctrl18month.HURLEY_SCORE as c18_hurley_score, 
--   ctrl18month.RA as c18_ra, 
--   ctrl18month.RAN as c18_ran, 
--   ctrl18month.RAF as c18_raf, 
--   ctrl18month.RALD as c18_rald, 
--   ctrl18month.RAHUR as c18_rahur, 
--   ctrl18month.RG as c18_rg, 
--   ctrl18month.RGN as c18_rgn, 
--   ctrl18month.RGF as c18_rgf,
--   ctrl18month.RGLD as c18_rgld, 
--   ctrl18month.RGHUR as c18_rghur, 
--   ctrl18month.RGR as c18_rgr, 
--   ctrl18month.RGRN as c18_rgrn, 
--   ctrl18month.RGRF as c18_rgrf, 
--   ctrl18month.RGRLD as c18_rgrld, 
--   ctrl18month.RGRHUR as c18_rgrhur, 
--   ctrl18month.LA as c18_la, 
--   ctrl18month.LAN as c18_lan, 
--   ctrl18month.LAF as c18_laf, 
--   ctrl18month.LALD as c18_lald, 
--   ctrl18month.LAHUR as c18_lahur, 
--   ctrl18month.LG as c18_lg, 
--   ctrl18month.LGN as c18_lgn,
--   ctrl18month.LGF as c18_lgf,
--   ctrl18month.LGLD as c18_lgld, 
--   ctrl18month.LGHUR as c18_lghur,
--   ctrl18month.LGR as c18_lgr, 
--   ctrl18month.LGRN as c18_lgrn, 
--   ctrl18month.LGRF as c18_lgrf,
--   ctrl18month.LGRLD as c18_lgrld, 
--   ctrl18month.LGRHUR as c18_lgrhur, 
--   ctrl18month.OTHERREGION as c18_otherregion, 
--   ctrl18month.ORN as c18_orn, 
--   ctrl18month.ORF as c18_orf, 
--   ctrl18month.ORLD as c18_orld,
--   ctrl18month.ORHUR as c18_orhur,
--   ctrl18month.HSSCORESUM as c18_hsscoresum, 
--   ctrl18month.SURGERY_TYPE as c18_surgery_type, 
--   ctrl18month.AKSILLE as c18_aksille, 
--   ctrl18month.AKSILLE_RIGHT as c18_aksille_right, 
--   ctrl18month.AKSILLE_LEFT as c18_aksille_left, 
--   ctrl18month.AKSILLE_UNKNOWN as c18_aksille_unknown, 
--   ctrl18month.LYSKE as c18_lyske, 
--   ctrl18month.LYSKE_RIGHT as c18_lyske_right,  
--   ctrl18month.LYSKE_LEFT as c18_lyske_left,  
--   ctrl18month.LYSKE_UNKNOWN as c18_lyske_unknown,
--   ctrl18month.PUBIS as c18_pubis, 
--   ctrl18month.PUBIS_RIGHT as c18_pubis_right,  
--   ctrl18month.PUBIS_LEFT as c18_pubis_left, 
--   ctrl18month.PUBIS_CENTRAL as c18_pubis_central, 
--   ctrl18month.PUBIS_UNKNOWN as c18_pubis_unknown, 
--   ctrl18month.GENITALT as c18_genitalt, 
--   ctrl18month.GENITALT_RIGHT as c18_genitalt_right,  
--   ctrl18month.GENITALT_LEFT as c18_genitalt_left,   
--   ctrl18month.GENITALT_UNKNOWN as c18_genitalt_unknown,   
--   ctrl18month.PERIALT as c18_peritalt,  
--   ctrl18month.PERIALT_RIGHT as c18_peritalt_right, 
--   ctrl18month.PERIALT_LEFT as c18_peritalt_left, 
--   ctrl18month.PERIALT_UNKNOWN as c18_peritalt_unknown, 
--   ctrl18month.GLUTEALT as c18_glutealt, 
--   ctrl18month.GLUTEALT_RIGHT as c18_glutealt_right, 
--   ctrl18month.GLUTEALT_LEFT as c18_glutealt_left, 
--   ctrl18month.GLUTEALT_CENTRAL as c18_glutealt_central, 
--   ctrl18month.GLUTEALT_UNKNOWN as c18_glutealt_unknown, 
--   ctrl18month.MAMMAE as c18_mammae, 
--   ctrl18month.MAMMAE_RIGHT as c18_right, 
--   ctrl18month.MAMMAE_LEFT as c18_left, 
--   ctrl18month.MAMMAE_UNKNOWN as c18_unknown, 
--   ctrl18month.OTHER_LOCATION as c18_other_location, 
--   ctrl18month.OTHER_LOCATION_THIGHS as c18_other_location_thighs,  
--   ctrl18month.OTHER_LOCATION_STOMACH as c18_other_location_stomach,  
--   ctrl18month.OTHER_LOCATION_BACK as c18_other_location_back,  
--   ctrl18month.OTHER_LOCATION_NECK as c18_other_location_neck,  
--   ctrl18month.OTHER_LOCATION_OTHER as c18_other_location_other, 
--   ctrl18month.OTHER_LOCATION_OTHER_TEXT as c18_other_location_other_text,  
--   ctrl18month.INFECTION as c18_infection, 
--   ctrl18month.DELAYED_WOUND_HEALING as c18_delayed_wound_healing, 
--   ctrl18month.STRIKTURER as c18_stricturer,
--   ctrl18month.NERVEDAMAGE as c18_nervedamage, 
--   ctrl18month.BLOODPOISEN as c18_bloodpoisoning, 
--   ctrl18month.BLEEDING as c18_bleeding, 
--   ctrl18month.OTHER_COMPLICATIONS as c18_other_complications, 
--   ctrl18month.OTHER_COMPLICATIONS_TEXT as c18_other_complications_text,
--   ctrl18month.BIOLOGICAL_TREATMENT as c18_biological_treatment,  
--   ctrl18month.STOP_MEDICAL_TREATMENT as c18_medical_treatment, 
--   ctrl18month.SYSTEMIC_ANTIBIOTIC_THERAPY as c18_systemic_antibiotic_therapy, 
--   ctrl18month.SYSTEMIC_ANTIBIOTIC_THERAPY_STOP as c18_systemic_antibiotic_therapy_stop,  
--   ctrl18month.ANTIINFLAMMATORY_TREATMENT as c18_antiinflammatory_treatment, 
--   ctrl18month.ANTIINFLAMMATORY_TREATMENT_STOP as c18_antiinflammatory_treatment_stop, 
--   ctrl18month.ANALGESICS as c18_analgesics, 
--   ctrl18month.ANALGESICS_STOP as c18_analgesics_stop, 
--   ctrl18month.INTRALESIONAL_CORTICOSTEROID_INJECTION as c18_corticosteroid_injection, 
--   ctrl18month.INTRALESIONAL_CORTICOSTEROID_INJECTION_STOP as c18_corticosteroid_injection_stop, 
--   ctrl18month.ACELACIC_ACID as c18_acelacic_acid, 
--   ctrl18month.ACELACIC_ACID_STOP as c18_acelacic_acid_stop, 
--   ctrl18month.CLINDAMYCIN as c18_clindamycin, 
--   ctrl18month.CLINDAMYCIN_STOP as c18_clindamycin_stop, 
--   ctrl18month.RESORCINOL as c18_resorcinol, 
--   ctrl18month.RESORCINOL_STOP as c18_resorcinol_stop, 
--   ctrl18month.MEDICAL_INT_OTHER as c18_other_medication, 
--   ctrl18month.MEDICAL_INT_OTHER_STOP as c18_other_medication_stop, 
--   ctrl18month.HISCR_BOILS as c18_hiscr_boils,
--   ctrl18month.HISCR_INFLAMED as c18_hiscr_inflamed,
--   ctrl18month.HISCR_DRAINING as c18_hiscr_draining,     
--   ctrl18month.STATUS as c18_status,
--   
--   ctrl21month.CENTREID as c21_centreid, 
--   ctrl21month.DO_MONTH as c21_do_month, 
--   ctrl21month.CONTROL_DATE as c21_date, 
--   ctrl21month.POSSIBLE as c21_possible,
--   ctrl21month.IMPOSSIBLE_REASON as c21_impossible_reason,
--   ctrl21month.IMPOSSIBLE_OTHER_REASON as c21_impossible_reason_other,  
--   ctrl21month.ABSCESS as c21_abscess, 
--   ctrl21month.ABSCESS_PAIN as c21_abscess_pain, 
--   ctrl21month.VASSCORE as c21_vasscore, 
--   ctrl21month.WORK as c21_work, 
--   ctrl21month.SORNESS as c21_soreness, 
--   ctrl21month.EMBARRESSED as c21_embarressed, 
--   ctrl21month.PREVENT_DAILY_WORK as c21_prevent_daily_work, 
--   ctrl21month.CLOTHING_OPTION as c21_clothing_option, 
--   ctrl21month.SOCIAL_LIFE as c21_social_life, 
--   ctrl21month.ATHLETIC_ACTIVITY as c21_athletic_activity, 
--   ctrl21month.PREVENT_WORK as c21_prevent_work, 
--   ctrl21month.WORK_PROBLEMS as c21_work_problems, 
--   ctrl21month.PARTNER_PROBLEMS as c21_parnter_problems, 
--   ctrl21month.SEXUAL_PROBLEMS as c21_sexual_problems, 
--   ctrl21month.PROBLEMS_LAST_WEEK as c21_problems_last_week, 
--   ctrl21month.DLQISUM as c21_dlqisum, 
--   ctrl21month.HURLEY_SCORE as c21_hurley_score, 
--   ctrl21month.RA as c21_ra, 
--   ctrl21month.RAN as c21_ran, 
--   ctrl21month.RAF as c21_raf, 
--   ctrl21month.RALD as c21_rald, 
--   ctrl21month.RAHUR as c21_rahur, 
--   ctrl21month.RG as c21_rg, 
--   ctrl21month.RGN as c21_rgn, 
--   ctrl21month.RGF as c21_rgf,
--   ctrl21month.RGLD as c21_rgld, 
--   ctrl21month.RGHUR as c21_rghur, 
--   ctrl21month.RGR as c21_rgr, 
--   ctrl21month.RGRN as c21_rgrn, 
--   ctrl21month.RGRF as c21_rgrf, 
--   ctrl21month.RGRLD as c21_rgrld, 
--   ctrl21month.RGRHUR as c21_rgrhur, 
--   ctrl21month.LA as c21_la, 
--   ctrl21month.LAN as c21_lan, 
--   ctrl21month.LAF as c21_laf, 
--   ctrl21month.LALD as c21_lald, 
--   ctrl21month.LAHUR as c21_lahur, 
--   ctrl21month.LG as c21_lg, 
--   ctrl21month.LGN as c21_lgn,
--   ctrl21month.LGF as c21_lgf,
--   ctrl21month.LGLD as c21_lgld, 
--   ctrl21month.LGHUR as c21_lghur,
--   ctrl21month.LGR as c21_lgr, 
--   ctrl21month.LGRN as c21_lgrn, 
--   ctrl21month.LGRF as c21_lgrf,
--   ctrl21month.LGRLD as c21_lgrld, 
--   ctrl21month.LGRHUR as c21_lgrhur, 
--   ctrl21month.OTHERREGION as c21_otherregion, 
--   ctrl21month.ORN as c21_orn, 
--   ctrl21month.ORF as c21_orf, 
--   ctrl21month.ORLD as c21_orld,
--   ctrl21month.ORHUR as c21_orhur,
--   ctrl21month.HSSCORESUM as c21_hsscoresum, 
--   ctrl21month.SURGERY_TYPE as c21_surgery_type, 
--   ctrl21month.AKSILLE as c21_aksille, 
--   ctrl21month.AKSILLE_RIGHT as c21_aksille_right, 
--   ctrl21month.AKSILLE_LEFT as c21_aksille_left, 
--   ctrl21month.AKSILLE_UNKNOWN as c21_aksille_unknown, 
--   ctrl21month.LYSKE as c21_lyske, 
--   ctrl21month.LYSKE_RIGHT as c21_lyske_right,  
--   ctrl21month.LYSKE_LEFT as c21_lyske_left,  
--   ctrl21month.LYSKE_UNKNOWN as c21_lyske_unknown,
--   ctrl21month.PUBIS as c21_pubis, 
--   ctrl21month.PUBIS_RIGHT as c21_pubis_right,  
--   ctrl21month.PUBIS_LEFT as c21_pubis_left, 
--   ctrl21month.PUBIS_CENTRAL as c21_pubis_central, 
--   ctrl21month.PUBIS_UNKNOWN as c21_pubis_unknown, 
--   ctrl21month.GENITALT as c21_genitalt, 
--   ctrl21month.GENITALT_RIGHT as c21_genitalt_right,  
--   ctrl21month.GENITALT_LEFT as c21_genitalt_left,   
--   ctrl21month.GENITALT_UNKNOWN as c21_genitalt_unknown,   
--   ctrl21month.PERIALT as c21_peritalt,  
--   ctrl21month.PERIALT_RIGHT as c21_peritalt_right, 
--   ctrl21month.PERIALT_LEFT as c21_peritalt_left, 
--   ctrl21month.PERIALT_UNKNOWN as c21_peritalt_unknown, 
--   ctrl21month.GLUTEALT as c21_glutealt, 
--   ctrl21month.GLUTEALT_RIGHT as c21_glutealt_right, 
--   ctrl21month.GLUTEALT_LEFT as c21_glutealt_left, 
--   ctrl21month.GLUTEALT_CENTRAL as c21_glutealt_central, 
--   ctrl21month.GLUTEALT_UNKNOWN as c21_glutealt_unknown, 
--   ctrl21month.MAMMAE as c21_mammae, 
--   ctrl21month.MAMMAE_RIGHT as c21_right, 
--   ctrl21month.MAMMAE_LEFT as c21_left, 
--   ctrl21month.MAMMAE_UNKNOWN as c21_unknown, 
--   ctrl21month.OTHER_LOCATION as c21_other_location, 
--   ctrl21month.OTHER_LOCATION_THIGHS as c21_other_location_thighs,  
--   ctrl21month.OTHER_LOCATION_STOMACH as c21_other_location_stomach,  
--   ctrl21month.OTHER_LOCATION_BACK as c21_other_location_back,  
--   ctrl21month.OTHER_LOCATION_NECK as c21_other_location_neck,  
--   ctrl21month.OTHER_LOCATION_OTHER as c21_other_location_other, 
--   ctrl21month.OTHER_LOCATION_OTHER_TEXT as c21_other_location_other_text,  
--   ctrl21month.INFECTION as c21_infection, 
--   ctrl21month.DELAYED_WOUND_HEALING as c21_delayed_wound_healing, 
--   ctrl21month.STRIKTURER as c21_stricturer,
--   ctrl21month.NERVEDAMAGE as c21_nervedamage, 
--   ctrl21month.BLOODPOISEN as c21_bloodpoisoning, 
--   ctrl21month.BLEEDING as c21_bleeding, 
--   ctrl21month.OTHER_COMPLICATIONS as c21_other_complications, 
--   ctrl21month.OTHER_COMPLICATIONS_TEXT as c21_other_complications_text,
--   ctrl21month.BIOLOGICAL_TREATMENT as c21_biological_treatment,  
--   ctrl21month.STOP_MEDICAL_TREATMENT as c21_medical_treatment, 
--   ctrl21month.SYSTEMIC_ANTIBIOTIC_THERAPY as c21_systemic_antibiotic_therapy, 
--   ctrl21month.SYSTEMIC_ANTIBIOTIC_THERAPY_STOP as c21_systemic_antibiotic_therapy_stop,  
--   ctrl21month.ANTIINFLAMMATORY_TREATMENT as c21_antiinflammatory_treatment, 
--   ctrl21month.ANTIINFLAMMATORY_TREATMENT_STOP as c21_antiinflammatory_treatment_stop, 
--   ctrl21month.ANALGESICS as c21_analgesics, 
--   ctrl21month.ANALGESICS_STOP as c21_analgesics_stop, 
--   ctrl21month.INTRALESIONAL_CORTICOSTEROID_INJECTION as c21_corticosteroid_injection, 
--   ctrl21month.INTRALESIONAL_CORTICOSTEROID_INJECTION_STOP as c21_corticosteroid_injection_stop, 
--   ctrl21month.ACELACIC_ACID as c21_acelacic_acid, 
--   ctrl21month.ACELACIC_ACID_STOP as c21_acelacic_acid_stop, 
--   ctrl21month.CLINDAMYCIN as c21_clindamycin, 
--   ctrl21month.CLINDAMYCIN_STOP as c21_clindamycin_stop, 
--   ctrl21month.RESORCINOL as c21_resorcinol, 
--   ctrl21month.RESORCINOL_STOP as c21_resorcinol_stop, 
--   ctrl21month.MEDICAL_INT_OTHER as c21_other_medication, 
--   ctrl21month.MEDICAL_INT_OTHER_STOP as c21_other_medication_stop, 
--   ctrl21month.HISCR_BOILS as c21_hiscr_boils,
--   ctrl21month.HISCR_INFLAMED as c21_hiscr_inflamed,
--   ctrl21month.HISCR_DRAINING as c21_hiscr_draining,     
--   ctrl21month.STATUS as c21_status,
--   
--   ctrl24month.CENTREID as c24_centreid, 
--   ctrl24month.DO_MONTH as c24_do_month, 
--   ctrl24month.CONTROL_DATE as c24_date, 
--   ctrl24month.POSSIBLE as c24_possible,
--   ctrl24month.IMPOSSIBLE_REASON as c24_impossible_reason,
--   ctrl24month.IMPOSSIBLE_OTHER_REASON as c24_impossible_reason_other,  
--   ctrl24month.ABSCESS as c24_abscess, 
--   ctrl24month.ABSCESS_PAIN as c24_abscess_pain, 
--   ctrl24month.VASSCORE as c24_vasscore, 
--   ctrl24month.WORK as c24_work, 
--   ctrl24month.SORNESS as c24_soreness, 
--   ctrl24month.EMBARRESSED as c24_embarressed, 
--   ctrl24month.PREVENT_DAILY_WORK as c24_prevent_daily_work, 
--   ctrl24month.CLOTHING_OPTION as c24_clothing_option, 
--   ctrl24month.SOCIAL_LIFE as c24_social_life, 
--   ctrl24month.ATHLETIC_ACTIVITY as c24_athletic_activity, 
--   ctrl24month.PREVENT_WORK as c24_prevent_work, 
--   ctrl24month.WORK_PROBLEMS as c24_work_problems, 
--   ctrl24month.PARTNER_PROBLEMS as c24_parnter_problems, 
--   ctrl24month.SEXUAL_PROBLEMS as c24_sexual_problems, 
--   ctrl24month.PROBLEMS_LAST_WEEK as c24_problems_last_week, 
--   ctrl24month.DLQISUM as c24_dlqisum, 
--   ctrl24month.HURLEY_SCORE as c24_hurley_score, 
--   ctrl24month.RA as c24_ra, 
--   ctrl24month.RAN as c24_ran, 
--   ctrl24month.RAF as c24_raf, 
--   ctrl24month.RALD as c24_rald, 
--   ctrl24month.RAHUR as c24_rahur, 
--   ctrl24month.RG as c24_rg, 
--   ctrl24month.RGN as c24_rgn, 
--   ctrl24month.RGF as c24_rgf,
--   ctrl24month.RGLD as c24_rgld, 
--   ctrl24month.RGHUR as c24_rghur, 
--   ctrl24month.RGR as c24_rgr, 
--   ctrl24month.RGRN as c24_rgrn, 
--   ctrl24month.RGRF as c24_rgrf, 
--   ctrl24month.RGRLD as c24_rgrld, 
--   ctrl24month.RGRHUR as c24_rgrhur, 
--   ctrl24month.LA as c24_la, 
--   ctrl24month.LAN as c24_lan, 
--   ctrl24month.LAF as c24_laf, 
--   ctrl24month.LALD as c24_lald, 
--   ctrl24month.LAHUR as c24_lahur, 
--   ctrl24month.LG as c24_lg, 
--   ctrl24month.LGN as c24_lgn,
--   ctrl24month.LGF as c24_lgf,
--   ctrl24month.LGLD as c24_lgld, 
--   ctrl24month.LGHUR as c24_lghur,
--   ctrl24month.LGR as c24_lgr, 
--   ctrl24month.LGRN as c24_lgrn, 
--   ctrl24month.LGRF as c24_lgrf,
--   ctrl24month.LGRLD as c24_lgrld, 
--   ctrl24month.LGRHUR as c24_lgrhur, 
--   ctrl24month.OTHERREGION as c24_otherregion, 
--   ctrl24month.ORN as c24_orn, 
--   ctrl24month.ORF as c24_orf, 
--   ctrl24month.ORLD as c24_orld,
--   ctrl24month.ORHUR as c24_orhur,
--   ctrl24month.HSSCORESUM as c24_hsscoresum, 
--   ctrl24month.SURGERY_TYPE as c24_surgery_type, 
--   ctrl24month.AKSILLE as c24_aksille, 
--   ctrl24month.AKSILLE_RIGHT as c24_aksille_right, 
--   ctrl24month.AKSILLE_LEFT as c24_aksille_left, 
--   ctrl24month.AKSILLE_UNKNOWN as c24_aksille_unknown, 
--   ctrl24month.LYSKE as c24_lyske, 
--   ctrl24month.LYSKE_RIGHT as c24_lyske_right,  
--   ctrl24month.LYSKE_LEFT as c24_lyske_left,  
--   ctrl24month.LYSKE_UNKNOWN as c24_lyske_unknown,
--   ctrl24month.PUBIS as c24_pubis, 
--   ctrl24month.PUBIS_RIGHT as c24_pubis_right,  
--   ctrl24month.PUBIS_LEFT as c24_pubis_left, 
--   ctrl24month.PUBIS_CENTRAL as c24_pubis_central, 
--   ctrl24month.PUBIS_UNKNOWN as c24_pubis_unknown, 
--   ctrl24month.GENITALT as c24_genitalt, 
--   ctrl24month.GENITALT_RIGHT as c24_genitalt_right,  
--   ctrl24month.GENITALT_LEFT as c24_genitalt_left,   
--   ctrl24month.GENITALT_UNKNOWN as c24_genitalt_unknown,   
--   ctrl24month.PERIALT as c24_peritalt,  
--   ctrl24month.PERIALT_RIGHT as c24_peritalt_right, 
--   ctrl24month.PERIALT_LEFT as c24_peritalt_left, 
--   ctrl24month.PERIALT_UNKNOWN as c24_peritalt_unknown, 
--   ctrl24month.GLUTEALT as c24_glutealt, 
--   ctrl24month.GLUTEALT_RIGHT as c24_glutealt_right, 
--   ctrl24month.GLUTEALT_LEFT as c24_glutealt_left, 
--   ctrl24month.GLUTEALT_CENTRAL as c24_glutealt_central, 
--   ctrl24month.GLUTEALT_UNKNOWN as c24_glutealt_unknown, 
--   ctrl24month.MAMMAE as c24_mammae, 
--   ctrl24month.MAMMAE_RIGHT as c24_right, 
--   ctrl24month.MAMMAE_LEFT as c24_left, 
--   ctrl24month.MAMMAE_UNKNOWN as c24_unknown, 
--   ctrl24month.OTHER_LOCATION as c24_other_location, 
--   ctrl24month.OTHER_LOCATION_THIGHS as c24_other_location_thighs,  
--   ctrl24month.OTHER_LOCATION_STOMACH as c24_other_location_stomach,  
--   ctrl24month.OTHER_LOCATION_BACK as c24_other_location_back,  
--   ctrl24month.OTHER_LOCATION_NECK as c24_other_location_neck,  
--   ctrl24month.OTHER_LOCATION_OTHER as c24_other_location_other, 
--   ctrl24month.OTHER_LOCATION_OTHER_TEXT as c24_other_location_other_text,  
--   ctrl24month.INFECTION as c24_infection, 
--   ctrl24month.DELAYED_WOUND_HEALING as c24_delayed_wound_healing, 
--   ctrl24month.STRIKTURER as c24_stricturer,
--   ctrl24month.NERVEDAMAGE as c24_nervedamage, 
--   ctrl24month.BLOODPOISEN as c24_bloodpoisoning, 
--   ctrl24month.BLEEDING as c24_bleeding, 
--   ctrl24month.OTHER_COMPLICATIONS as c24_other_complications, 
--   ctrl24month.OTHER_COMPLICATIONS_TEXT as c24_other_complications_text,
--   ctrl24month.BIOLOGICAL_TREATMENT as c24_biological_treatment,  
--   ctrl24month.STOP_MEDICAL_TREATMENT as c24_medical_treatment, 
--   ctrl24month.SYSTEMIC_ANTIBIOTIC_THERAPY as c24_systemic_antibiotic_therapy, 
--   ctrl24month.SYSTEMIC_ANTIBIOTIC_THERAPY_STOP as c24_systemic_antibiotic_therapy_stop,  
--   ctrl24month.ANTIINFLAMMATORY_TREATMENT as c24_antiinflammatory_treatment, 
--   ctrl24month.ANTIINFLAMMATORY_TREATMENT_STOP as c24_antiinflammatory_treatment_stop, 
--   ctrl24month.ANALGESICS as c24_analgesics, 
--   ctrl24month.ANALGESICS_STOP as c24_analgesics_stop, 
--   ctrl24month.INTRALESIONAL_CORTICOSTEROID_INJECTION as c24_corticosteroid_injection, 
--   ctrl24month.INTRALESIONAL_CORTICOSTEROID_INJECTION_STOP as c24_corticosteroid_injection_stop, 
--   ctrl24month.ACELACIC_ACID as c24_acelacic_acid, 
--   ctrl24month.ACELACIC_ACID_STOP as c24_acelacic_acid_stop, 
--   ctrl24month.CLINDAMYCIN as c24_clindamycin, 
--   ctrl24month.CLINDAMYCIN_STOP as c24_clindamycin_stop, 
--   ctrl24month.RESORCINOL as c24_resorcinol, 
--   ctrl24month.RESORCINOL_STOP as c24_resorcinol_stop, 
--   ctrl24month.MEDICAL_INT_OTHER as c24_other_medication, 
--   ctrl24month.MEDICAL_INT_OTHER_STOP as c24_other_medication_stop, 
--   ctrl24month.HISCR_BOILS as c24_hiscr_boils,
--   ctrl24month.HISCR_INFLAMED as c24_hiscr_inflamed,
--   ctrl24month.HISCR_DRAINING as c24_hiscr_draining,     
--   ctrl24month.STATUS as c24_status  
-- from patient
-- join mce ON patient.PID = mce.PID
-- join registration ON registration.MCEID = mce.MCEID
-- join preintervention ON preintervention.MCEID = mce.MCEID
-- join intervention ON intervention.MCEID = mce.MCEID
-- left outer join control ctrl3month ON ctrl3month.MCEID = mce.MCEID 
--   and ctrl3month.STATUS = 1 
--   and ctrl3month.DO_MONTH = 3
-- left outer join control ctrl6month ON ctrl6month.MCEID = mce.MCEID 
--   and ctrl6month.STATUS = 1 
--   and ctrl6month.DO_MONTH = 6
-- left outer join control ctrl9month ON ctrl9month.MCEID = mce.MCEID 
--   and ctrl9month.STATUS = 1 
--   and ctrl9month.DO_MONTH = 9  
-- left outer join control ctrl12month ON ctrl12month.MCEID = mce.MCEID 
--   and ctrl12month.STATUS = 1 
--   and ctrl12month.DO_MONTH = 12   
-- left outer join control ctrl15month ON ctrl15month.MCEID = mce.MCEID 
--   and ctrl15month.STATUS = 1 
--   and ctrl15month.DO_MONTH = 15  
-- left outer join control ctrl18month ON ctrl18month.MCEID = mce.MCEID 
--   and ctrl18month.STATUS = 1 
--   and ctrl18month.DO_MONTH = 18   
-- left outer join control ctrl21month ON ctrl21month.MCEID = mce.MCEID 
--   and ctrl21month.STATUS = 1 
--   and ctrl21month.DO_MONTH = 21    
-- left outer join control ctrl24month ON ctrl24month.MCEID = mce.MCEID 
--   and ctrl24month.STATUS = 1 
--   and ctrl24month.DO_MONTH = 24  
-- where preintervention.STATUS = 1 and intervention.STATUS = 1 and patient.STATUS = 1  
-- order by patient.PID, mce.MCEID;  
from patient
join mce ON patient.PID = mce.PID
join registration ON registration.MCEID = mce.MCEID
join preintervention ON preintervention.MCEID = mce.MCEID
join intervention ON intervention.MCEID = mce.MCEID

left outer join control ctrl6month ON ctrl6month.MCEID = mce.MCEID 
  and ctrl6month.STATUS = 1 

-- left outer join control ctrl3month ON ctrl3month.MCEID = mce.MCEID 
--   and ctrl3month.STATUS = 1 
--   and ctrl3month.DO_MONTH = 3
-- left outer join control ctrl6month ON ctrl6month.MCEID = mce.MCEID 
--   and ctrl6month.STATUS = 1 
--   and ctrl6month.DO_MONTH = 6
-- left outer join control ctrl9month ON ctrl9month.MCEID = mce.MCEID 
--   and ctrl9month.STATUS = 1 
--   and ctrl9month.DO_MONTH = 9  
-- left outer join control ctrl12month ON ctrl12month.MCEID = mce.MCEID 
--   and ctrl12month.STATUS = 1 
--   and ctrl12month.DO_MONTH = 12   
-- left outer join control ctrl15month ON ctrl15month.MCEID = mce.MCEID 
--   and ctrl15month.STATUS = 1 
--   and ctrl15month.DO_MONTH = 15  
-- left outer join control ctrl18month ON ctrl18month.MCEID = mce.MCEID 
--   and ctrl18month.STATUS = 1 
--   and ctrl18month.DO_MONTH = 18   
-- left outer join control ctrl21month ON ctrl21month.MCEID = mce.MCEID 
--   and ctrl21month.STATUS = 1 
--   and ctrl21month.DO_MONTH = 21    
-- left outer join control ctrl24month ON ctrl24month.MCEID = mce.MCEID 
--   and ctrl24month.STATUS = 1 
--   and ctrl24month.DO_MONTH = 24    
  
where preintervention.STATUS = 1 and intervention.STATUS = 1 and patient.STATUS = 1
order by patient.PID, mce.MCEID;    
